backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'email_templates'
    identifier_field: name
    label: 'Email Template'
    folder: 'content/email-templates'
    create: true
    extension: yaml
    format: yaml
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Innovation (Custom Widget Test)', name: 'widget-test', widget: 'innovation' }
      - label: Components
        name: components
        widget: list
        summary: '{{fields.kind}} {{fields.description}}'
        fields:
          - label: 'Select component'
            name: 'kind'
            widget: 'select'
            options: ['Header', 'Amount', 'Footer', 'Name', 'Intro', 'Banner']
          - { label: 'Required', name: 'required', widget: 'boolean' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - label: Sub-Components
            name: subComponents
            widget: list
            summary: '{{fields.kind}}'
            fields:
              - label: 'Select sub-component'
                name: 'kind'
                widget: 'select'
                options:
                  - { label: 'Footer - Additional Content', value: 'AdditionalContent' }
                  - { label: 'Header - Title', value: 'Title' }
                  - { label: 'Header - Label', value: 'Label' }
                  - { label: 'Amount - Breakdown', value: 'Breakdown' }
                  - { label: 'Footer - Additional Content', value: 'AdditionalContent' }
              - { label: 'Required', name: 'required', widget: 'boolean' }
