backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'email_templates'
    identifier_field: name
    label: 'Email Template'
    folder: 'content/email-templates'
    create: true
    extension: yaml
    format: yaml
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Innovation (Custom Widget Test)', name: 'widget-test', widget: 'innovation' }
      - label: Components
        name: components
        widget: list
        summary: '{{fields.kind}} {{fields.description}}'
        fields:
          - label: 'Select component'
            name: 'kind'
            widget: 'select'
            options: ['Banner', 'Header', 'Name', 'Body', 'Footer', 'Disclaimer']
          - { label: 'Required', name: 'required', widget: 'boolean' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - label: Sub-Components
            name: subComponents
            widget: list
            summary: '{{fields.kind}}'
            fields:
              - label: 'Select sub-component'
                name: 'kind'
                widget: 'select'
                options:
                  - { label: 'Header - Title', value: 'Title' }
                  - { label: 'Header - Program Name', value: 'ProgramName' }
                  - { label: 'Body - Intro', value: 'Intro' }
                  - {
                      label: 'Body - Rules, Rights, and Regulations',
                      value: 'RulesRightsRegulations',
                    }
                  - { label: 'Body - Status', value: 'Status' }
                  - { label: 'Body - Supplemental Content', value: 'SupplementalContent' }
                  - { label: 'Body - Directive', value: 'Directive' }
                  - { label: 'Body - LoginDetails', value: 'LoginDetails' }
                  - { label: 'Footer - Additional Content', value: 'AdditionalContent' }
              - { label: 'Required', name: 'required', widget: 'boolean' }
              - { label: 'Description', name: 'description', widget: 'text' }
