backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'email_templates'
    identifier_field: name
    label: 'Email Template'
    folder: 'content/email-templates'
    create: true
    extension: yaml
    format: yaml
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Innovation (Custom Widget Test)', name: 'widget-test', widget: 'innovation' }
      - label: Components
        name: components
        widget: list
        summary: '{{fields.component}} - {{fields.description}}'
        fields:
          - label: 'Select component'
            name: 'component'
            widget: 'select'
            options: ['Header', 'Footer', 'Intro']
          - { label: 'Description', name: 'description', widget: 'text' }
