name: DUA Application Confirmation
description: Disaster Unemployment Assistance Application Confirmation
appModes: ["ALL", "NJ"]
components:
  - kind: Banner
    required: true
  - kind: Header
    required: true
    subComponents:
      - kind: DepartmentSeal
        required: true
      - kind: Title
        visibleByDefault: true
        description: Keep this short and to the point!
        defaultValue:
          title: "Application Received"
      - kind: ProgramName
        visibleByDefault: true
        defaultValue:
          preset: "Disaster Unemployment Assistance (DUA)"
          name: "Disaster Unemployment Assistance (DUA)"
          backgroundColor: "#CCBDDF"
  - kind: Name
    visibleByDefault: true
    description: Adding a name is highly encouraged. Avoid using "Dear" before the name
    defaultValue:
      name: "{!EADJ_ISSUE__C.EADJ_CLAIMANT_NAME__C}:"
  - kind: Body
    required: true
    subComponents:
      - kind: Intro
        visibleByDefault: true
        description: Keep it simple and clear. Don't use filler language like "please" or
        defaultValue:
          intro:
            - type: paragraph
              children:
                - text: Your Disaster Unemployment Assistance (DUA) application is
            - type: paragraph
              children:
                - text: ""
            - type: paragraph
              children:
                - text: "You will receive:"
      - kind: Status
        visibleByDefault: true
        description: Make it obvious what the current state is
        defaultValue:
          variant: Overview
          icon: Warning
          status: Received &amp; Under Review
          statusDueTo: because...
          showSupportiveInformation: true
          spaceAfter: true
          description:
            - type: paragraph
              children:
                - text: It may take up to 2 weeks
                  bold: true
                - text: " to determine your eligibility."
          supportiveInformation:
            - type: paragraph
              children:
                - text: >-
                    If you are eligible, you will receive an email directing you to
                    complete your weekly certification.
                  italic: true
          documentsNeededLabel: "We need the following:"
          documentsNeededValue: "{Name_of_document(s)}"
          emailToLabel: "Email this to:"
          emailToValue: DUA@unemployment.gov
          subjectLineLabel: "Subject Line:"
          subjectLineValue: "Eligible Pending Review Documents<br/>{Name_of_claimant}"
          missingDocumentDeadline: >-
            If you do not submit your documents by 00/00/0000, you will be denied your
            claim and will be required to pay back any DUA funds released to you.
          boxColor: Yielding Yellow
          amountLabel: You owe $200
          overpaymentLabel: Overpayment Total
          overpaymentValue: $200
          waivedLabel: Amount waived
          waivedValue: $50
          totalLabel: You must pay
          totalValue: $150
      - kind: SupplementalContent
        visibleByDefault: true
        description: Add other resources that will help color the message you're sending
        defaultValue:
          variant: "Single Supplemental Content"
          title: You can only participate in one program<br>
          description:
            - type: paragraph
              children:
                - text: >-
                    Disaster Unemployment Assistance (DUA) replaces your Unemployment
                    Insurance (UI) certification process.
                - text: " "
                - text: You cannot participate in both.
                  bold: true
            - type: paragraph
              children:
                - bold: true
                  text: ""
            - type: paragraph
              children:
                - text: >-
                    You do not need to certify for Unemployment Insurance (UI) if you are
                    receiving DUA.
  - kind: Footer
    required: true
    subComponents:
      - kind: AdditionalContent
        visibleByDefault: true
        description: A great place to add links to find out more about programs and
          other state offerings. <strong>Do not use "click here"!</strong>
        defaultValue:
          content:
            - type: paragraph
              children:
                - text: >-
                    More information on New Jersey's Disaster Unemployment Assistance
                    (DUA) can be found
                - text: " "
                - type: link
                  url: >-
                    https://www.myunemployment.nj.gov/labor/myunemployment/apply/overpayments/
                  children:
                    - text: here
                - text: ".  Frequently Asked Questions can be found "
                - type: link
                  url: >-
                    https://www.myunemployment.nj.gov/labor/myunemployment/apply/overpayments/
                  children:
                    - text: here
                - text: .
  - kind: StateSeal
    required: true
  - kind: Disclaimer
    required: true
