name: Overpayment - Application
description: To invite claimants to apply for an overpayment waiver
appModes: ["ALL", "NJ"]
components:
  - kind: Banner
    required: true
  - kind: Header
    required: true
    subComponents:
      - kind: DepartmentSeal
        required: true
      - kind: Title
        required: true
        defaultValue:
          title: Reset your password
      - kind: ProgramName
        required: true
        defaultValue:
          preset: Custom
          name: Pandemic Unemployment Overpayment
          backgroundColor: "#f1dea0"
  - kind: Name
    required: true
    defaultValue:
      name: "{!eadj_UI_Case__c.eadj_Claimant_Name__c}:"
  - kind: Body
    required: true
    subComponents:
      - kind: Intro
        required: true
        defaultValue:
          intro:
            - type: paragraph
              children:
                - text: >-
                    You requested a waiver application for your Pandemic Unemployment
                    Overpayment.
      - kind: Directive
        required: true
        defaultValue:
          variant: One Step
          title: 'Apply &amp; Submit<span style="font-weight: normal;">&nbsp;waiver form:</span>'
          showTitle: true
          showLabel: true
          label:
            - type: paragraph
              children:
                - text: "To help resolve this issue, complete the following steps:"
          linkHref: "{!eadj_UI_Case__c.eadj_Custom_Link__c}"
          buttonLabel: Get Started
          buttonColor: "#1b1b1b"
          step1Label:
            - type: paragraph
              children:
                - text: Step 1 Directive
                  bold: true
          showStep1AdditionalContent: true
          step1Additional:
            - type: paragraph
              children:
                - text: Additional information around Step 1
          oneStepSupportiveText:
            - type: paragraph
              children:
                - text: "This link will expire on {!eadj_UI_Case__c.eadj_LinkExpirationDate__c}"
                  textSize: small
          step2Label:
            - type: paragraph
              children:
                - text: Step 2 Directive
                  bold: true
          showStep2AdditionalContent: true
          step2Additional:
            - type: paragraph
              children:
                - text: Additional information around Step 2
          step2Tertiary:
            - type: paragraph
              children:
                - text: >-
                    Tertiary information around Step 2, (usually involving an alternate
                    way to complete the second step).
          step2CaseNumber:
            - type: paragraph
              children:
                - text: "Case #: [000000]"
          step3Label:
            - type: paragraph
              children:
                - text: Step 3 Directive
                  bold: true
          showStep3AdditionalContent: true
          step3Additional:
            - type: paragraph
              children:
                - text: Additional information around Step 3
          showMultipleStepsSupportiveText: true
          multipleStepsSupportiveText:
            - type: paragraph
              children:
                - text: >-
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a
                    tellus nec eros placerat ornare at sed ante. Duis enim quam, auctor
                    quis congue eget, commodo eu urna. Donec laoreet a dui consequat
                    sollicitudin. Aliquam et dapibus ex, at malesuada tellus.
                  italic: true
          alternativePaymentLabel: >-
            Or, send a check here: <br>Bureau of Benefit Payment Control<br>c/o Refund
            Processing Station<br>P.O. Box 951<br>Trenton, NJ 08625-0951
          payOnlineSupportiveText:
            - type: paragraph
              children:
                - text: >-
                    Make the check or money order payable to NJ Dept. of Labor and
                    Workforce Development. Be sure to write your name and social security
                    number on the payment.
      - kind: RulesRightsRegulations
        required: true
        defaultValue:
          variant: Reminder
          icon: Flag
          boxColor: Governing Gray
          reminderTitle: Reminder
          reminderDescription:
            - type: paragraph
              children:
                - text: You may only be eligible for this waiver if...
                  bold: true
            - type: paragraph
              children:
                - bold: true
                  text: ""
            - type: numbered-list
              children:
                - type: list-item
                  children:
                    - bold: true
                      text: Overpayment was due to no fault of your own*
                - type: list-item
                  children:
                    - bold: true
                      text: Repayment would be unfair and unreasonable given the context
            - type: paragraph
              children:
                - bold: true
                  text: ""
            - type: paragraph
              children:
                - text: >-
                    This waiver is for Pandemic Unemployment Assistance (PUA), Federal
                    Pandemic Unemployment Compensation (FPUC), Mixed Earners Unemployment
                    Compensation (MEUC), and Pandemic Extended Unemployment Compensation
                    (PEUC).
                  italic: true
            - type: paragraph
              children:
                - text: ""
            - type: paragraph
              children:
                - text: >-
                    *State and federal laws, rules, and guidance will be used to make
                    these determinations.
                  bold: true
                  textSize: small
          appealRightsTitle: Appeal Rights
          appealRightsSummary:
            - type: paragraph
              children:
                - text: >-
                    If you disagree with this determination, you have the right to file an
                    appeal. Your appeal must be received within seven (7) days after the
                    date you received this email.
          appealRightsShowInstruction: true
          appealRightsInstruction:
            - type: paragraph
              children:
                - text: "To begin an appeal online, get started below:"
          appealRightsButton: Get Started
          appealRightsHref: >-
            https://link.embedded-into-the-button-above.should-be-shown-here-in-order-to-give-an-alternative-way-to-access-a-link
          appealRightsShowInfoLabel: true
          appealRightsInfoLabel: "For your appeal:"
          appealRightsShowInfo: true
          appealRightsInfo:
            - type: paragraph
              children:
                - text: "Program Code:"
                  bold: true
                - text: "  ###"
            - type: paragraph
              children:
                - text: "Date of Claim:"
                  bold: true
                - text: "  00/00/0000"
            - type: paragraph
              children:
                - text: "Date of Determination:"
                  bold: true
                - text: "  00/00/0000"
          yourRightsTitle: "Your Rights:"
          showYourRightsDescription: true
          yourRightsDescription:
            - type: paragraph
              children:
                - text: >-
                    A dependent is an unemployed spouse/civil union partner or an
                    unemployed, unmarried child (including stepchild or legally adopted
                    child) under the age of 19 (or 22 if the child is attending school
                    full-time).
                  italic: true
          yourRightsList:
            - type: numbered-list
              children:
                - type: list-item
                  children:
                    - text: >-
                        You may represent yourself or you may be represented at your own
                        expense by an attorney or non-attorney
                - type: list-item
                  children:
                    - text: >-
                        You may request a postponement, if you require additional time to
                        prepare your response to this questionnaire
                - type: list-item
                  children:
                    - text: >-
                        You may request that your employer produce any documents which
                        relate to your eligibility for benefits
                - type: list-item
                  children:
                    - text: >-
                        You may request that statements be taken from your witnesses who
                        have firsthand knowledge of the case
                - type: list-item
                  children:
                    - text: >-
                        You or your representative will have the opportunity to provide
                        witness statements, present documents and provide a closing
                        statement or summary
                - type: list-item
                  children:
                    - text: >-
                        If the reason for the questionnaire is related to your employment,
                        any questions that you may have for your former employer may be
                        included on the form and the reviewing claims examiner may, at
                        his/her discretion, pose the question(s) to your former employer.
      - kind: LoginDetails
        required: true
        defaultValue:
          variant: Details
          loginDetailsTitle: Login Details
          usernameLabel: "Your username is:"
          usernameValue: "{!EADJ_UI_CASE__C.eadj_Claimant_Email_c}"
          resetPasswordMessage:
            - type: paragraph
              children:
                - text: >-
                    If you're having trouble logging in, send a request to reset your
                    password.
          button: Reset Password
          buttonHref: >-
            https://forms.office.com/Pages/ResponsePage.aspx?id=0cN2UAI4n0uzauCkG9ZCp8zTKxTpe0RMmjY7qrMr_3BUOFlVUklYTzhDQjlWR0NaMVk1NjBQODJDWCQlQCN0PWcu
          resetPasswordDetails:
            - type: paragraph
              children:
                - text: >-
                    Your request may take up to 7-10 business days. An email will be sent
                    to you when your password has been reset.
                  italic: true
          loginDetailsIcon: Lock
          loginInformationTitle: Important Login Information
          loginInformationDescription:
            - type: paragraph
              children:
                - text: >-
                    Login using the same Login ID and Password you used to file your
                    claim.
                  bold: true
          showLoginInformationBody: true
          loginInformationBody:
            - type: bulleted-list
              children:
                - type: list-item
                  children:
                    - text: "If you do not have an account,"
                      bold: true
                      italic: true
                    - text: " create one here. After creating your account, return to this email and get started."
                      italic: true
                - type: list-item
                  children:
                    - text: Forget your username and password?
                      bold: true
                      italic: true
                    - text: " Follow the links on the login page to help access your account."
                      italic: true
          loginInformationIcon: LockOpen
  - kind: Footer
    required: true
    subComponents:
      - kind: AdditionalContent
        required: true
        defaultValue:
          content:
            - type: paragraph
              children:
                - text: "More information  on Pandemic Overpayment Waivers can be found "
                - type: link
                  url: >-
                    https://www.myunemployment.nj.gov/labor/myunemployment/apply/overpayments/
                  children:
                    - text: here
                - text: .
