name: Waiver Application
description: Often used for campaigns, or general registration announcements.
components:
  - kind: Header
    subComponents:
      - kind: Title
        required: true
      - kind: ProgramName
  - kind: Name
    description: Adding a name is highly encouraged
  - kind: Body
    subComponents:
      - kind: Intro
      - kind: Directive
      - kind: SupplementalContent
  - kind: Footer
    subComponents:
      - kind: AdditionalContent
  - kind: Disclaimer
