name: Waiver Application
description: Often used for campaigns, or general registration announcements.
appModes: ["ALL", "NJ", "KY"]
templates:
  - language: english
    components:
      - kind: Banner
        required: true
      - kind: Header
        subComponents:
          - kind: DepartmentSeal
            required: true
          - kind: Title
            required: true
          - kind: ProgramName
      - kind: Name
      - kind: Body
        required: true
        subComponents:
          - kind: Intro
          - kind: Directive
          - kind: SupplementalContent
          - kind: SupplementalContent
      - kind: Footer
        subComponents:
          - kind: AdditionalContent
      - kind: StateSeal
        required: true
      - kind: Disclaimer
        required: true
